export const FIGHTING_STYLES = {
  BOXING: "Boxing",
  MUAY_THAI: "Muay Thai", 
  JU_JITSU: "Ju Jitsu",
  MIXED_MARTIAL_ARTS: "MMA",
  BJJ: "BJJ",
  KICKBOXING: "Kickboxing",
  KRAV_MAGA: "Krav Maga",
  WRESTLING: "Wrestling",
  KIDS: "Kids",
  JUDO: "Judo",
  YOGA: "Yoga"
};

export const FIGHTING_STYLES_ARRAY = [
  FIGHTING_STYLES.BOXING,
  FIGHTING_STYLES.MUAY_THAI,
  FIGHTING_STYLES.JU_JITSU,
  FIGHTING_STYLES.MIXED_MARTIAL_ARTS,
  FIGHTING_STYLES.BJJ,
  FIGHTING_STYLES.KICKBOXING,
  FIGHTING_STYLES.KRAV_MAGA,
  FIGHTING_STYLES.WRESTLING,
  FIGHTING_STYLES.KIDS,
  FIGHTING_STYLES.JUDO,
  FIGHTING_STYLES.YOGA
]; 