export const FIGHTING_STYLES = {
  BOXING: "Boxing",
  MUAY_THAI: "Muay Thai", 
  MIXED_MARTIAL_ARTS: "MMA",
  KICKBOXING: "Kickboxing",
  KRAV_MAGA: "Krav Maga",
  WRESTLING: "Wrestling",
  JU_JITSU: "Ju-Jitsu",
  JUDO: "Judo",
  CAPOEIRA: "Capoeira",
  KARATE: "Karate",
  TAEKWONDO: "Taekwondo",
  WINGCHUN: "Win Chun",
  KUNGFU: "Kung fu",
  TAICHI: "Tai chi"
};

export const FIGHTING_STYLES_ARRAY = [
  FIGHTING_STYLES.MIXED_MARTIAL_ARTS,
  FIGHTING_STYLES.MUAY_THAI,
  FIGHTING_STYLES.KICKBOXING,
  FIGHTING_STYLES.BOXING,
  FIGHTING_STYLES.WRESTLING,
  FIGHTING_STYLES.JU_JITSU,
  FIGHTING_STYLES.JUDO,
  FIGHTING_STYLES.KARATE,
  FIGHTING_STYLES.TAEKWONDO,
  FIGHTING_STYLES.WINGCHUN,
  FIGHTING_STYLES.CAPOEIRA,
  FIGHTING_STYLES.KRAV_MAGA
]; 