export const FIGHTING_STYLES = {
  BOXING: "Boxing",
  MUAY_THAI: "Muay Thai", 
  JU_JITSU: "Ju Jitsu",
  MIXED_MARTIAL_ARTS: "Mixed Martial Arts"
};

export const FIGHTING_STYLES_ARRAY = [
  FIGHTING_STYLES.BOXING,
  FIGHTING_STYLES.MUAY_THAI,
  FIGHTING_STYLES.JU_JITSU,
  FIGHTING_STYLES.MIXED_MARTIAL_ARTS
]; 